[tool:pytest]
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = --verbosity=2 --tb=short --ds=fastcp.settings
testpaths = . api core
markers =
    unit: Unit tests
    integration: Integration tests
    slow: Slow running tests
env =
    IS_DEBUG=1
    DJANGO_SETTINGS_MODULE=fastcp.settings
