# Generated by Django 5.2.6 on 2025-09-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20210915_1518"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="website",
            name="php",
            field=models.CharField(choices=[("8.4", "PHP 8.4"), ("8.3", "PHP 8.3")], max_length=20),
        ),
    ]
