# Generated by Django 5.2.6 on 2025-09-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_password_alter_website_php'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='php',
            field=models.CharField(choices=[('8.2', 'PHP 8.2'), ('8.1', 'PHP 8.1'), ('8.0', 'PHP 8.0'), ('7.4', 'PHP 7.4'), ('7.3', 'PHP 7.3')], max_length=20),
        ),
    ]
