name: Feature Request
description: Create a feature request
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: request
    attributes:
      label: Describe the feature Request
    validations:
      required: true
  - type: dropdown
    id: ubuntuversion
    attributes:
      label: Do this feature need third party software like redis for example?
      options:
        - Yes
        - No
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Which area is targeted by the feature request?
      multiple: true
      options:
        - Server Management
        - Databases
        - Webserver
        - Security
        - Apps
        - User Management
        - Web-GUI
        - Software
        - anything else
