"""Add initial website model.

Revision ID: a89bb80a647e
Revises: 
Create Date: 2025-06-09 15:56:06.345792

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89bb80a647e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'websites',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('system_user_id', sa.Integer(), nullable=False),
        sa.Column(
            'label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            'php_version', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_websites_system_user_id'), 'websites', ['system_user_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_websites_system_user_id'), table_name='websites')
    op.drop_table('websites')
    # ### end Alembic commands ###
